// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import fs from "node:fs";
import path from "node:path";
import dotenv from "dotenv";
import { defineConfig } from "prisma/config";

const rootDir = process.cwd();
const envFiles = [".env", ".env.local", ".env.production"];

for (const envFile of envFiles) {
  const fullPath = path.join(rootDir, envFile);
  if (fs.existsSync(fullPath)) {
    dotenv.config({ path: fullPath, override: true });
  }
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"] || "postgresql://postgres:postgres@localhost:5433/oceny",
  },
});
